import{S as v,i as m,a as L}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="/goit-js-hw-12/assets/bi_x-octagon-378f247e.svg",u=document.querySelector(".js-search-form"),c=document.querySelector(".gallery");let i=document.querySelector(".loader"),a;const g=new v(".gallery a",{captionsData:"alt",captionDelay:250});let d=1,f=15,p;const w=async r=>{r.preventDefault();const t=r.target.elements.search.value;if(a=document.querySelector(".loadBtn"),a&&a.remove(),t!==""){d=1,c.innerHTML="",u.insertAdjacentHTML("afterend",'<span class="loader"></span>'),i=document.querySelector(".loader");const s=await h(t);setTimeout(()=>{i&&i.remove(),y(s.hits),p=Math.ceil(s.totalHits/f),d<p?T(t):s.hits.length!==0&&m.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})},500)}u.reset()},h=async r=>(await L.get("https://pixabay.com/api/",{params:{key:"42121827-736028e2edd071afefc989558",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:d}})).data;function y(r){if(r.length===0)return m.show({message:"Sorry, there are no images matching<br>your search query. Please try again!",messageColor:"rgba(255, 255, 255, 1)",backgroundColor:"rgba(239, 64, 64, 1)",iconUrl:S,position:"topRight"});const t=q(r);c.insertAdjacentHTML("beforeend",t),g.on("show.simplelightbox"),g.refresh()}function q(r){return r.map(({largeImageURL:t,webformatURL:s,tags:n,likes:e,views:o,comments:l,downloads:b})=>`<li class="gallery-item">
            <div class="image-container">
                <a href="${t}"><img src="${s}" alt="${n}" class="gallery-image"></a>
            </div>
            <div class="gallery-card">
                <p><span class="description">Likes</span>${e}</p>
                <p><span class="description">Views</span>${o}</p>
                <p><span class="description">Comments</span>${l}</p>
                <p><span class="description">Downloads</span>${b}</p>
            </div>
        </li>`).join("")}function T(r){c.insertAdjacentHTML("afterend",'<button type="button" class="loadBtn">Load more</button>'),a=document.querySelector(".loadBtn"),a.addEventListener("click",async()=>{a.insertAdjacentHTML("beforebegin",'<span class="loader"></span>'),a.remove(),d+=1;const t=await h(r);setTimeout(()=>{i=document.querySelector(".loader"),i&&i.remove(),y(t.hits),c.parentNode.insertBefore(a,c.nextSibling),d>=p&&(a.remove(),m.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}));const s=document.querySelector(".gallery-item:last-child");if(s){const n=s.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}},500)})}u.addEventListener("submit",w);
//# sourceMappingURL=commonHelpers.js.map
